import { AIProvider, AIDecisionInput, AIDecisionOutput } from "./provider";

export class MockAIProvider implements AIProvider {
  private modelVersion: string;

  constructor(modelVersion = "mock-proofmind-v1") {
    this.modelVersion = modelVersion;
  }

  async generateDecision(input: AIDecisionInput): Promise<AIDecisionOutput> {
    console.log(`[MockAIProvider] Processing input signal for subject: ${input.subject}`);

    // Deterministic logic based on input signal value
    let decision: "ALLOW" | "REJECT" | "REVIEW" = "ALLOW";
    let action: "APPROVE_LIMIT" | "NO_ACTION" | "FLAG_REVIEW" = "APPROVE_LIMIT";
    let score = 90;
    let limit = "1500000000000000000000"; // 1500 tokens in wei

    if (input.signalValue > 80) {
      decision = "REJECT";
      action = "NO_ACTION";
      score = 45;
      limit = "0";
    } else if (input.signalValue > 50) {
      decision = "REVIEW";
      action = "FLAG_REVIEW";
      score = 75;
      limit = "500000000000000000000"; // 500 tokens in wei
    }

    return {
      decision,
      score,
      action,
      limit,
      reasoning_summary: `Signal value is ${input.signalValue}. Structured decision proposal generated by mock.`,
      modelVersion: this.modelVersion,
      expiresAt: Math.floor(Date.now() / 1000) + 3600, // 1 hour expiry
    };
  }
}
